# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fanuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
