# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161101_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
